---
# packages required + extra
preservicaservice_packages:
 - python3.6-dev
 - python3.6-venv
 - python3.6
 - git
 - build-essential
 - libffi-dev
 - libssl-dev
 - libxml2-dev
 - rsyslog
 - openjdk-8-jdk-headless

# enable extra details in image
preservicaservice_debug_mode: false
# extra packages for debug
preservicaservice_packages_debug:
 - curl
 - htop
 - iftop
 - iotop
 - openssh-client
 - openssh-server
 - rsync
 - strace
 - sudo
 - tmux
 - unzip
 - vim
 - wget

# which user to run service under, defines install path as well
preservicaservice_username: preservicaservice
# syslog facility
preservicaservice_syslog_facility: local0
# file to redirect syslog
preservicaservice_syslog_folder: /var/log/preservicaservice
preservicaservice_syslog_file: '{{preservicaservice_syslog_folder}}/debug.log'
# installation folder
preservicaservice_install_path: '/home/{{preservicaservice_username}}/app'
# environment file
preservicaservice_systemd_env_filepath: '/etc/preservicaservice.env'
