sudo: required
language: python

python:
  - "3.5-dev"

before_install:
  - >
      travis_retry curl
      "https://releases.hashicorp.com/terraform/0.10.8/terraform_0.10.8_linux_amd64.zip"
      > /tmp/terraform.zip
  - sudo unzip /tmp/terraform.zip -d /usr/bin
  - sudo chmod +x /usr/bin/terraform

install:
  - make deps

script:
  - make lint
  - make test
