dist: xenial
sudo: required
language: python
env:
  global:
    - TERRAFORM_VERSION=0.10.8

python:
  - "3.5-dev"

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - >
      travis_retry curl
      "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
      > /tmp/terraform.zip
  - sudo unzip /tmp/terraform.zip -d /usr/bin
  - sudo chmod +x /usr/bin/terraform

install:
  - make deps

script:
  - make lint
  - make test
