---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: '%(process)d [%(levelname)s] %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

loggers:
    preservicaservice:
        level: DEBUG
        handlers: [console]
        propagate: no

root:
    level: DEBUG
    handlers: [console]
