---
- name: install packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
    cache_valid_time: 60
  with_items: '{{preservicaservice_packages}}'

- name: install debug packages
  apt:
    name: '{{item}}'
    state: present
    update_cache: yes
    cache_valid_time: 60
  with_items: '{{preservicaservice_packages_debug}}'
  when: preservicaservice_debug_mode|bool
